/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

/**
 *
 * @author DEll
 */
public class ActorsForm extends javax.swing.JFrame {

    /**
     * Creates new form ActorsForm
     */
    public ActorsForm() {
        initComponents();
        setExtendedState(ActorsForm.MAXIMIZED_HORIZ);
	setVisible(true);
	setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adminBtn = new com.k33ptoo.components.KButton();
        exeBtn = new com.k33ptoo.components.KButton();
        empBtn = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actor Selection");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(187, 187, 187));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(50, 0, 0, 0, new java.awt.Color(116, 2, 2)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 170, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 140));

        jPanel2.setBackground(new java.awt.Color(187, 187, 187));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 100, 0, new java.awt.Color(116, 2, 2)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 130, 660));

        jPanel3.setBackground(new java.awt.Color(187, 187, 187));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 100, 0, new java.awt.Color(116, 2, 2)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(223, 228, 234));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WWW.MAXDESIGNHUB.COM");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1010, 140));

        jLabel4.setBackground(new java.awt.Color(223, 228, 234));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(162, 13, 20));
        jLabel4.setText("You Want To Login As :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        adminBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        adminBtn.setText("ADMINISTRATOR");
        adminBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        adminBtn.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        adminBtn.setkEndColor(new java.awt.Color(162, 13, 20));
        adminBtn.setkHoverEndColor(new java.awt.Color(0, 0, 153));
        adminBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 367, 64));

        exeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        exeBtn.setText("EXECUTIVE");
        exeBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        exeBtn.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        exeBtn.setkEndColor(new java.awt.Color(162, 13, 20));
        exeBtn.setkHoverEndColor(new java.awt.Color(0, 0, 153));
        exeBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        exeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 367, 64));

        empBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        empBtn.setText("EMPLOYEE");
        empBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        empBtn.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        empBtn.setkEndColor(new java.awt.Color(162, 13, 20));
        empBtn.setkHoverEndColor(new java.awt.Color(0, 0, 153));
        empBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        empBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBtnActionPerformed(evt);
            }
        });
        getContentPane().add(empBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 367, 64));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/buttonLogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1010, 570));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4));
        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(66, 35));

        jMenu1.setBackground(new java.awt.Color(255, 153, 0));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jMenu1.setForeground(new java.awt.Color(255, 153, 0));
        jMenu1.setText("File");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFocusPainted(true);
        jMenu1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 24));

        exitBtn.setBackground(new java.awt.Color(6, 82, 221));
        exitBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setFocusPainted(true);
        exitBtn.setPreferredSize(new java.awt.Dimension(100, 28));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jMenu1.add(exitBtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jMenu2.setForeground(new java.awt.Color(255, 153, 0));
        jMenu2.setText("Help");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFocusPainted(true);
        jMenu2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(100, 25));

        aboutBtn.setBackground(new java.awt.Color(6, 82, 221));
        aboutBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("About Us");
        aboutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        aboutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutBtn.setFocusPainted(true);
        aboutBtn.setPreferredSize(new java.awt.Dimension(100, 28));
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jMenu2.add(aboutBtn);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1129, 791));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:
        AboutUsForm ab = new AboutUsForm();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
        AdminLoginForm ab = new AdminLoginForm();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminBtnActionPerformed

    private void exeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeBtnActionPerformed
        // TODO add your handling code here:
        ExeLoginForm ab = new ExeLoginForm();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exeBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        ExitConfirmation ab = new ExitConfirmation();
        ab.setVisible(true);
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void empBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empBtnActionPerformed
        // TODO add your handling code here:
        EmpLoginForm f = new EmpLoginForm();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActorsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutBtn;
    private com.k33ptoo.components.KButton adminBtn;
    private com.k33ptoo.components.KButton empBtn;
    private com.k33ptoo.components.KButton exeBtn;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
