/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author DEll
 */
public class AddDProject extends javax.swing.JInternalFrame {

    String full;
    
    /**
     * Creates new form AddDProject
     */
    public AddDProject() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    public String fileData()
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               ADD Project\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Ayesha | Accountant\n\n";
               s += "                           Data Details are as follows :\n\n";
               return s;
    }
    
    public String FullData(String ProName)
    {
        String data = "";
        data += "***************************************************************************************\n";
        data += "*                                 MAX DESIGNS                                         *\n";
        data += "***************************************************************************************\n\n";
        data += "                            "+ProName+" Project\n";
        data += "_______________________________________________________________________________________\n\n";
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        invalidName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        locTxt = new javax.swing.JTextField();
        invalidLoaction = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ownerTxt = new javax.swing.JTextField();
        invalidOwner = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cnicTxt = new javax.swing.JTextField();
        invalidCnic = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        invalidContact = new javax.swing.JLabel();
        houseTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        invalidHouse = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sectorTxt = new javax.swing.JTextField();
        invalidSector = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        serviceBox = new javax.swing.JComboBox<>();
        invalidAmount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 728));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 169, 91));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Add Projects");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 80));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Name  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 40));

        nameTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(51, 0, 51));
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 250, 40));

        invalidName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidName.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(invalidName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 250, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Location :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 40));

        locTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        locTxt.setForeground(new java.awt.Color(51, 0, 51));
        locTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(locTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 250, 40));

        invalidLoaction.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidLoaction.setForeground(new java.awt.Color(153, 0, 0));
        invalidLoaction.setText("(Area(City))");
        jPanel1.add(invalidLoaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 250, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Owner Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 40));

        ownerTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        ownerTxt.setForeground(new java.awt.Color(51, 0, 51));
        ownerTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(ownerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 250, 40));

        invalidOwner.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidOwner.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(invalidOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 250, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Owner CNIC :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 40));

        cnicTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        cnicTxt.setForeground(new java.awt.Color(51, 0, 51));
        cnicTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(cnicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 250, 40));

        invalidCnic.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidCnic.setForeground(new java.awt.Color(153, 0, 0));
        invalidCnic.setText("(Only digits required)");
        invalidCnic.setToolTipText("");
        jPanel1.add(invalidCnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 250, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Owner Contact :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, 40));

        contactTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        contactTxt.setForeground(new java.awt.Color(51, 0, 51));
        contactTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(contactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 250, 40));

        invalidContact.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidContact.setForeground(new java.awt.Color(153, 0, 0));
        invalidContact.setText("(Only digits required)");
        invalidContact.setToolTipText("");
        jPanel1.add(invalidContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 250, 30));

        houseTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        houseTxt.setForeground(new java.awt.Color(51, 0, 51));
        houseTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(houseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 240, 40));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("House No. :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 110, 40));

        invalidHouse.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidHouse.setForeground(new java.awt.Color(153, 0, 0));
        invalidHouse.setText("(Digits greater than 0)");
        jPanel1.add(invalidHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 240, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("Services :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 90, 40));

        sectorTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        sectorTxt.setForeground(new java.awt.Color(51, 0, 51));
        sectorTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(sectorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 240, 40));

        invalidSector.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidSector.setForeground(new java.awt.Color(153, 0, 0));
        invalidSector.setText("(Digits greater than 0)");
        jPanel1.add(invalidSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 240, 30));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("Sector :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 70, 40));

        serviceBox.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        serviceBox.setForeground(new java.awt.Color(51, 0, 51));
        serviceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Architecture", "Interior", "Decor" }));
        serviceBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        serviceBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(serviceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 240, 40));

        invalidAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidAmount.setForeground(new java.awt.Color(153, 0, 0));
        invalidAmount.setText("(Amount should be greater than 0)");
        jPanel1.add(invalidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 250, 30));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Amount :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 90, 40));

        amountTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        amountTxt.setForeground(new java.awt.Color(51, 0, 51));
        amountTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel1.add(amountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 240, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("ID :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 50, 40));

        idTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        idTxt.setForeground(new java.awt.Color(51, 0, 51));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        idTxt.setDisabledTextColor(new java.awt.Color(51, 0, 51));
        idTxt.setEnabled(false);
        jPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 240, 40));

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("ADD");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 3));
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxt.getText();
        String house = houseTxt.getText();
        String location = locTxt.getText();
        String sector = sectorTxt.getText();
        String owner = ownerTxt.getText();
        String services = serviceBox.getSelectedItem().toString();
        String cnic = cnicTxt.getText();
        String amount = amountTxt.getText();
        String contact = contactTxt.getText();
        
        if(name.equals(null) || name.equals("") || house.equals("") || house.equals(null) || location.equals(null) || location.equals("") || sector.equals("") || sector.equals(null) || owner.equals("") || owner.equals(null) || cnic.equals("") || cnic.equals(null) || amount.equals(null) || amount.equals("") || contact.equals("") || contact.equals(null))
        {
            if(name.equals(null) || name.equals(""))
            {
                invalidName.setText("Empty Field");
            }
            else
                invalidName.setText("");
            
            if(house.equals("") || house.equals(null))
            {
                invalidHouse.setText("Empty Field");
            }
            else {
                invalidHouse.setVisible(true);
                invalidHouse.setText("");
            }
            if(location.equals(null) || location.equals(""))
            {
                invalidLoaction.setText("Empty Field");
            }
            else
                invalidLoaction.setText("");
            
            if(sector.equals("") || sector.equals(null))
            {
                invalidSector.setText("Empty Field");
            }
            else
                invalidSector.setText("");
            
            if(owner.equals("") || owner.equals(null))
            {
                invalidOwner.setText("Empty Field");
            }
            else
                invalidOwner.setText("");
            
            if(cnic.equals("") || cnic.equals(null))
            {
                invalidCnic.setText("Empty Field");
            }
            else
                invalidCnic.setText("");
            
            if(amount.equals(null) || amount.equals(""))
            {
                invalidAmount.setText("empty Field");
            }
            else
                invalidAmount.setText("");
            
            if(contact.equals("") || contact.equals(null))
            {
                invalidContact.setText("Empty Field");
            }
            else
                invalidContact.setText("");
                
                
        }
        else
        {
            invalidLoaction.setText("");
            invalidContact.setText("");
            invalidCnic.setText("");
            invalidAmount.setText("");
            invalidHouse.setText("");
            invalidSector.setText("");
            invalidOwner.setText("");
            
            DesignProjects d = new DesignProjects(services);
            d.setDate(java.time.LocalDate.now().toString());
            if(d.setName(name))
            {
                invalidName.setText("");
                invalidHouse.setVisible(true);
                this.full = FullData(name);
//                System.out.println(full);
                String data = fileData();
                data += "Project Name : "+name+"\n";
                if(d.setLocaction(location))
                {
                    invalidLoaction.setText("");
                    invalidHouse.setVisible(true);
                    invalidHouse.setText("");
                    if(d.isDigits(house))
                    {
                        invalidHouse.setText("");
                        int h = Integer.parseInt(house);
                        if(d.setHouse(h))
                        {
                            invalidHouse.setText("");
                            if(d.isDigits(sector))
                            {
                                invalidSector.setText("");
                                int s = Integer.parseInt(sector);
                                if(d.setSector(s))
                                {
                                    invalidHouse.setText("");
                                    invalidSector.setText("");
                                    this.full += "Address : House no. "+d.getHouse()+", "+d.getLocation()+", Sector-"+d.getSector()+"\n";
                                    data += "House Address : "+"House no. "+house+" ( Sector : "+sector+" ), "+"Location : "+location+"\n";
                                    if(d.setOwner(owner))
                                    {
                                        invalidOwner.setText("");
                                        invalidHouse.setText("");
                                        data += "Owner : "+owner+"\n";
                                        this.full += "Owner of the House : "+owner+"\n";
                                        
                                        if(d.setCnic(cnic))
                                        {
                                            invalidCnic.setText("");
                                            invalidHouse.setText("");
                                            data += "CNIC : "+cnic+"\n";
                                            this.full += "CNIC of Owner : "+cnic+"\n";
                                            if(d.setContact(contact))
                                            {
                                                invalidContact.setText("");
                                                invalidHouse.setText("");
                                                data += "Contact : "+contact+"\n";
                                                this.full += "Contact of Owner : "+contact+"\n";
                                                if(d.isDigits(amount))
                                                {
                                                    invalidAmount.setText("");
                                                    int a = Integer.parseInt(amount);
                                                    if(d.setAmount(a))
                                                    {
                                                        invalidAmount.setText("");
                                                        invalidHouse.setText("");
                                                        this.full += "The amount Decided : Rs-"+a+" Only\n";
                                                        data += "Amount decided is : Rs-"+amount+"\n\n";
                                                        d.setID();
                                                        d.setBalance(d.getAmount());
                                                        idTxt.setText(d.getId());
                                                        data += "The ID generated is : "+d.getId()+"\n\n\n";
                                                        full += "ID Generated is : "+d.getId()+"\n";
                                                        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                                                        LocalDateTime now = LocalDateTime.now(); 
                                                        full += "Date/Time : "+dtf.format(now)+"\n";
                                                        full += "                                     MAX DESIGNS\n";
                                                        full += "_______________________________________________________________________________________\n\n";
                                                        data += "                                     MAX DESIGNS\n";
                                                        data += "____________________________________________________________________________\n\n";
                                                        MaxDesigns.getInstance().getDes().add(d);
                                                        MaxDesigns.getInstance().DrawWrite(data);
                                                        MaxDesigns.getInstance().writeDes();
                                                        MaxDesigns.getInstance().SeperateDraw(d.getName(),full);
                                                        JOptionPane.showMessageDialog(this,"Data Added successfully");
                                                    }
                                                    else
                                                        invalidAmount.setText("It should be greater than 0");
                                                }
                                                else
                                                    invalidAmount.setText("Amount should in digits");
                                            }
                                            else
                                                invalidContact.setText("Invalid Contact");
                                        }
                                        else
                                            invalidCnic.setText("Invalid Cnic");
                                        
                                    }
                                    else
                                        invalidOwner.setText("Invalid Owner");
                                }
                                else
                                    invalidSector.setText("Sector should be greater than 0");
                            }
                            else
                                invalidSector.setText("Sector should be a digit");
                        }
                        else {
                            
                            invalidHouse.setText("house no should be greater than 0");
                        }
                    }
                    else 
                        invalidHouse.setText("House no should be a digit");
                }
                else
                    invalidLoaction.setText("invalid Location");
                
            }
            else
                invalidName.setText("Invalid Name");
        }
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JTextField cnicTxt;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JTextField houseTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel invalidAmount;
    private javax.swing.JLabel invalidCnic;
    private javax.swing.JLabel invalidContact;
    private javax.swing.JLabel invalidHouse;
    private javax.swing.JLabel invalidLoaction;
    private javax.swing.JLabel invalidName;
    private javax.swing.JLabel invalidOwner;
    private javax.swing.JLabel invalidSector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField locTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField ownerTxt;
    private javax.swing.JTextField sectorTxt;
    private javax.swing.JComboBox<String> serviceBox;
    // End of variables declaration//GEN-END:variables
}
