/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEll
 */
public class AddWorker extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddWorker
     */
    public AddWorker() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        tableSet();
        setDataToRow();
    }
    
    public void setDataToRow()
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object rowData[]=new Object[2];
        model.setRowCount(0);
        if(MaxDesigns.getInstance().getEmp().size()>0)
        {
            for(int i =0;i<MaxDesigns.getInstance().getEmp().size();i++)
            {
                rowData[0]=MaxDesigns.getInstance().getEmp().get(i).getID();
                rowData[1]=MaxDesigns.getInstance().getEmp().get(i).getName();
                model.addRow(rowData);

            }
        }
    }
    
    public void tableSet()
    {
        jScrollPane1.setBackground(new Color(0,0,0,0));
       jScrollPane1.setOpaque(false);
       jTable1.setOpaque(false);
       ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
       jScrollPane1.getViewport().setOpaque(false);
    }
    
    
    public String fileData()
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               ADD Worker\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Ayesha | Accountant\n\n";
               s += "                           Data Details are as follows :\n\n";
               return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        invalidName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        invalidEmail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        ageBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        statusBox = new javax.swing.JComboBox<>();
        invalidSalary = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        invalidContact = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailTxt = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 738));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 169, 91));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Add Employee");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, -1, 80));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setRowHeight(30);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 132, 403, 330));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 132, -1, 39));

        nameTxt.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(51, 0, 51));
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 133, 277, 39));

        invalidName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        invalidName.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(invalidName, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 179, 330, 26));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Email :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 212, -1, 39));

        emailTxt.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(51, 0, 51));
        emailTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 213, 277, 39));

        invalidEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        invalidEmail.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(invalidEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 265, 330, 26));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Gender :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 298, -1, 39));

        maleBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(maleBtn);
        maleBtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        maleBtn.setForeground(new java.awt.Color(51, 0, 51));
        maleBtn.setText("Male");
        jPanel1.add(maleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 302, -1, -1));

        femaleBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(femaleBtn);
        femaleBtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        femaleBtn.setForeground(new java.awt.Color(51, 0, 51));
        femaleBtn.setText("Female");
        jPanel1.add(femaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 298, 138, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Age :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 344, -1, 40));

        ageBox.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        ageBox.setForeground(new java.awt.Color(51, 0, 51));
        ageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35" }));
        ageBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        ageBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 344, 277, 40));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText(" Status :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 404, -1, -1));

        statusBox.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        statusBox.setForeground(new java.awt.Color(51, 0, 51));
        statusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Architect", "Accountant", "Market Manager", "Supervisor", "House Boy", "Kitchen Boy", "Draft Man", "Interior Designer", "Visualizer", "Site Supervisor", "Project Management Consultant", " " }));
        statusBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        statusBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(statusBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 397, 277, 40));

        invalidSalary.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        invalidSalary.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(invalidSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 501, 320, 26));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Salary :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 455, -1, 39));

        salTxt.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        salTxt.setForeground(new java.awt.Color(51, 0, 51));
        salTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel1.add(salTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 455, 277, 39));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("Contact :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 534, -1, 39));

        contactTxt.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        contactTxt.setForeground(new java.awt.Color(51, 0, 51));
        contactTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel1.add(contactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 535, 277, 39));

        invalidContact.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        invalidContact.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(invalidContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 581, 320, 26));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("Details of Education and others :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, 39));

        detailTxt.setColumns(20);
        detailTxt.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        detailTxt.setForeground(new java.awt.Color(51, 0, 51));
        detailTxt.setRows(5);
        detailTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jScrollPane2.setViewportView(detailTxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 400, 170));

        addBtn.setBackground(new java.awt.Color(51, 0, 51));
        addBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("ADD");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxt.getText();
        String email = emailTxt.getText();
        String gender = "";
        if(maleBtn.isSelected())
        {
            gender = "Male";
        }
        else if(femaleBtn.isSelected())
        {
            gender = "Female";
        }
        else
            gender = "";
        
        int age = Integer.parseInt(ageBox.getSelectedItem().toString());
        String status = statusBox.getSelectedItem().toString();
        
        String salary = salTxt.getText();
        String contact = contactTxt.getText();
        String detail = detailTxt.getText();
        
        if(name.equals("") || name.equals(null) || email.equals("") || email.equals(null) || gender.equals("") || gender.equals(null) || salary.equals("") || salary.equals(null) || contact.equals("") || contact.equals(null) || detail.equals("") || detail.equals(null))
        {
            if(name.equals("") || name.equals(null))
            {
                invalidName.setText("Field is Empty");
            }
            else
                invalidName.setText("");
            
            if(email.equals("") || email.equals(null))
                invalidEmail.setText("Field is Empty");
            else
                invalidEmail.setText("");
            
            if(gender.equals("") || gender.equals(null))
                JOptionPane.showMessageDialog(this,"You first need to specify the Gender","No Gender Chosen",JOptionPane.ERROR_MESSAGE);
            
            if(salary.equals("") || salary.equals(null))
                invalidSalary.setText("Field is Empty");
            else
                invalidSalary.setText("");
            
            if(contact.equals("") || contact.equals(null))
                invalidContact.setText("Field is Empty");
            else
                invalidContact.setText("");
            
            if(detail.equals("") || detail.equals(null))
                JOptionPane.showMessageDialog(this,"You have to enter the details of Education","Empty Field",JOptionPane.ERROR_MESSAGE);
                
        }
        else
        {
            Employee e = new Employee(gender,age,status);
            if(e.setName(name))
            {
                invalidName.setText("");
                String data = fileData();
                data += "Name : "+name+"( "+status+" )\n";
                data += "Gender : "+gender+"               Age : "+age+"\n";
                
                if(e.setEmail(email))
                {
                    invalidEmail.setText("");
                    data += "Email : "+email+"\n";
                    if(e.isDigits(salary))
                    {
                        invalidSalary.setText("");
                        int s = Integer.parseInt(salary);
                        if(e.setSalary(s))
                        {
                            invalidSalary.setText("");
                            data += "Salary Decided : "+salary+"\n";
                            if(e.setContact(contact))
                            {
                                invalidContact.setText("");
                                data += "Contact : "+contact+"\n";
                                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                                LocalDateTime now = LocalDateTime.now();
                                e.setDate(dtf.format(now));
                                e.setID();
                                data += "The ID generated is : "+e.getID()+"\n";
                                data += "The Education details are :-\n\n";
                                data += detail+"\n\n\n";
                                data += "                                                 MAX DESIGNS\n";
                                data += "_________________________________________________________________________________________\n";
                                
                                MaxDesigns.getInstance().getEmp().add(e);
                                MaxDesigns.getInstance().writeEmp();
                                MaxDesigns.getInstance().EmpWrite(data);
                                
                                setDataToRow();
                                
                                
                                
                            }
                            else
                                invalidContact.setText("Contact (11 digits) contains only digits");
                        }
                        else
                            invalidSalary.setText("Salary should be greater than 0");
                    }
                    else
                        invalidSalary.setText("Salary should be Only in digits");
                }
                else
                    invalidEmail.setText("Correct Format is (abutt2210@gmail.com)");
            }
            else
                invalidName.setText("Only aplphabets and spaces allowedin name");
        }
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> ageBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JTextArea detailTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JLabel invalidContact;
    private javax.swing.JLabel invalidEmail;
    private javax.swing.JLabel invalidName;
    private javax.swing.JLabel invalidSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField salTxt;
    private javax.swing.JComboBox<String> statusBox;
    // End of variables declaration//GEN-END:variables
}
