/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.awt.Color;
import java.time.LocalDateTime;
import java.text.SimpleDateFormat; 

/**
 *
 * @author DEll
 */
public class AdminMenuForm extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminMenuForm
     */
    public AdminMenuForm() {
        initComponents();
        dateLabel.setText(java.time.LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        workersBtn = new javax.swing.JButton();
        srchBtn = new javax.swing.JButton();
        designBtn = new javax.swing.JButton();
        consultBtn = new javax.swing.JButton();
        vendorBtn = new javax.swing.JButton();
        completeBtn = new javax.swing.JButton();
        recordBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AdminPane = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-close-window-48.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Umair Umar | Max  Designs Administrator");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 591, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 40));

        jPanel2.setBackground(new java.awt.Color(162, 13, 20));

        workersBtn.setBackground(new java.awt.Color(162, 13, 20));
        workersBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        workersBtn.setForeground(new java.awt.Color(255, 255, 255));
        workersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/empicon.png"))); // NOI18N
        workersBtn.setText("Workers Details");
        workersBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        workersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workersBtnActionPerformed(evt);
            }
        });

        srchBtn.setBackground(new java.awt.Color(162, 13, 20));
        srchBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        srchBtn.setForeground(new java.awt.Color(255, 255, 255));
        srchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/search icon.png"))); // NOI18N
        srchBtn.setText("Search Worker");
        srchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        srchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBtnActionPerformed(evt);
            }
        });

        designBtn.setBackground(new java.awt.Color(162, 13, 20));
        designBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        designBtn.setForeground(new java.awt.Color(255, 255, 255));
        designBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-design-30.png"))); // NOI18N
        designBtn.setText("<html> Drawing Designs <br>     Projects");
        designBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        designBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        designBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designBtnActionPerformed(evt);
            }
        });

        consultBtn.setBackground(new java.awt.Color(162, 13, 20));
        consultBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        consultBtn.setForeground(new java.awt.Color(255, 255, 255));
        consultBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-vastu-consultancy-50 (1).png"))); // NOI18N
        consultBtn.setText("<html>\nConsultancy\n<br>\nProjects");
        consultBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        consultBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultBtnActionPerformed(evt);
            }
        });

        vendorBtn.setBackground(new java.awt.Color(162, 13, 20));
        vendorBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        vendorBtn.setForeground(new java.awt.Color(255, 255, 255));
        vendorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/vendor.png"))); // NOI18N
        vendorBtn.setText("<html>\nVendor's\n<br>\nHospitality");
        vendorBtn.setActionCommand("Vendors Hospitality");
        vendorBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        vendorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vendorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorBtnActionPerformed(evt);
            }
        });

        completeBtn.setBackground(new java.awt.Color(162, 13, 20));
        completeBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        completeBtn.setForeground(new java.awt.Color(255, 255, 255));
        completeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/complete.png"))); // NOI18N
        completeBtn.setText("<html>\nComplete\n<br>\nProjects");
        completeBtn.setActionCommand("Vendors Hospitality");
        completeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        completeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        recordBtn.setBackground(new java.awt.Color(162, 13, 20));
        recordBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        recordBtn.setForeground(new java.awt.Color(255, 255, 255));
        recordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-save-30.png"))); // NOI18N
        recordBtn.setText("Records");
        recordBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        recordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(162, 13, 20));
        logoutBtn.setFont(new java.awt.Font("Swis721 Blk BT", 1, 15)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-sign-out-30.png"))); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setActionCommand("Vendors Hospitality");
        logoutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(srchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(designBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(consultBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vendorBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(completeBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(workersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(srchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(designBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(consultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(vendorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(completeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(recordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 790));

        jPanel4.setBackground(new java.awt.Color(162, 13, 20));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(255, 153, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-person-30.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Umair Umar");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date : ");

        dateLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Max Designs");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 940, 50));

        AdminPane.setBackground(new java.awt.Color(223, 228, 234));

        jPanel3.setBackground(new java.awt.Color(223, 228, 234));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/small logo.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 402, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Welcome to the System");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Mr. Umair Umar");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/p2.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, 340));

        jLabel14.setBackground(new java.awt.Color(223, 228, 234));
        jLabel14.setFont(new java.awt.Font("Harrington", 1, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("<html>\nHelping you Build Better<br>from Concept to Completion");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, 80));

        AdminPane.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AdminPaneLayout = new javax.swing.GroupLayout(AdminPane);
        AdminPane.setLayout(AdminPaneLayout);
        AdminPaneLayout.setHorizontalGroup(
            AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AdminPaneLayout.setVerticalGroup(
            AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(AdminPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 940, 740));

        setSize(new java.awt.Dimension(1178, 830));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        MaxDesigns.getInstance().writeEmp();
        MaxDesigns.getInstance().writeDes();
        MaxDesigns.getInstance().writeCon();
        MaxDesigns.getInstance().writeVen();
        System.exit(0); 
    }//GEN-LAST:event_jLabel1MouseClicked

    private void workersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workersBtnActionPerformed
        // TODO add your handling code here:
        AdminPane.removeAll();
        AdminWorkerDisplay a = new AdminWorkerDisplay();
        AdminPane.add(a).setVisible(true);
    }//GEN-LAST:event_workersBtnActionPerformed

    private void srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBtnActionPerformed
        // TODO add your handling code here:
        AdminPane.removeAll();
        AdminSearchWorkerForm a = new AdminSearchWorkerForm();
        AdminPane.add(a).setVisible(true);
    }//GEN-LAST:event_srchBtnActionPerformed

    private void designBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designBtnActionPerformed
        // TODO add your handling code here:
        AdminPane.removeAll();
        DrawingDesignDisplayForm a = new DrawingDesignDisplayForm();
        AdminPane.add(a).setVisible(true);
    }//GEN-LAST:event_designBtnActionPerformed

    private void consultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultBtnActionPerformed
        // TODO add your handling code here:
        AdminPane.removeAll();
        CosultancyDisplayForm a = new CosultancyDisplayForm();
        AdminPane.add(a).setVisible(true);
        
    }//GEN-LAST:event_consultBtnActionPerformed

    private void vendorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorBtnActionPerformed
        // TODO add your handling code here:
        VendorsLogin v = new VendorsLogin();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendorBtnActionPerformed

    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        // TODO add your handling code here:
        AdminPane.removeAll();
        CompleteProjectsDisplay a = new CompleteProjectsDisplay();
        AdminPane.add(a).setVisible(true);
    }//GEN-LAST:event_completeBtnActionPerformed

    private void recordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtnActionPerformed
        // TODO add your handling code here:
        AdminPane.removeAll();
        RecordDisplayForm a = new RecordDisplayForm();
        AdminPane.add(a).setVisible(true);
    }//GEN-LAST:event_recordBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        AdminLogoutForm a = new AdminLogoutForm(this);
        a.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AdminPane;
    private javax.swing.JButton completeBtn;
    private javax.swing.JButton consultBtn;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton designBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton recordBtn;
    private javax.swing.JButton srchBtn;
    private javax.swing.JButton vendorBtn;
    private javax.swing.JButton workersBtn;
    // End of variables declaration//GEN-END:variables
}
