/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author DEll
 */
public class CompleteProjects extends javax.swing.JInternalFrame {

    /**
     * Creates new form CompleteProjects
     */
    public CompleteProjects() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
    public String FullData()
    {
        String s = "\n______________________________________________________________________\n\n";
        s += "Congratulation Your Project Has been Completed !!!!!!!!!!!!!\n";
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now(); 
        s += "Date/Time : "+dtf.format(now)+"\n";
        s += "                                     MAX DESIGNS\n";
        s += "_______________________________________________________________________________________\n\n";
        return s;
    }
    
    public String fileData(int index, int type)
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               Project Completed\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Ayesha | Accountant\n\n";
               s += "                  Congratulation.....*\n\n";
               s += "                  __________________\n";
               
               if(type == 1)
               {
                   s += "Project Name : "+MaxDesigns.getInstance().getCon().get(index).getName()+" ( "+MaxDesigns.getInstance().getCon().get(index).getId()+" )\n";
                   s += "Owner Name : "+MaxDesigns.getInstance().getCon().get(index).getOwner()+" ( "+MaxDesigns.getInstance().getCon().get(index).getContact()+" )\n";
                   s += "Date Started :"+MaxDesigns.getInstance().getCon().get(index).getDate()+"\n\n\n";
                   s += "*******************************************************************\n";
                   s += "*                       Congatulation To The                      *\n";
                   s += "*                       Team Of MAX DESIGNS                       *\n";
                   s += "*******************************************************************\n\n\n";
                   s += "______________________________________________________________________________________________\n\n";
               }
               else if(type == 2)
               {
                   s += "Project Name : "+MaxDesigns.getInstance().getDes().get(index).getName()+" ( "+MaxDesigns.getInstance().getDes().get(index).getId()+" )\n";
                   s += "Owner Name : "+MaxDesigns.getInstance().getDes().get(index).getOwner()+" ( "+MaxDesigns.getInstance().getDes().get(index).getContact()+" )\n";
                   s += "Date Started :"+MaxDesigns.getInstance().getDes().get(index).getDate()+"\n\n\n";
                   s += "*******************************************************************\n";
                   s += "*                       Congatulation To The                      *\n";
                   s += "*                       Team Of MAX DESIGNS                       *\n";
                   s += "*******************************************************************\n\n\n";
                   s += "______________________________________________________________________________________________\n\n";
               }
               
               return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        consultBtn = new javax.swing.JRadioButton();
        drawBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        subBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 738));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/Logo (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Complete Projects");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Project Type :");

        consultBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(consultBtn);
        consultBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        consultBtn.setForeground(new java.awt.Color(51, 0, 51));
        consultBtn.setText("Consultancy");

        drawBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(drawBtn);
        drawBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        drawBtn.setForeground(new java.awt.Color(51, 0, 51));
        drawBtn.setText("Drawing Designs");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Project ID :");

        idTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        idTxt.setForeground(new java.awt.Color(51, 0, 51));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        subBtn.setBackground(new java.awt.Color(51, 0, 51));
        subBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        subBtn.setForeground(new java.awt.Color(255, 255, 255));
        subBtn.setText("SUBMIT");
        subBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        subBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drawBtn)
                            .addComponent(consultBtn)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(265, 265, 265))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(consultBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drawBtn))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idTxt))
                .addGap(30, 30, 30)
                .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        String text = idTxt.getText();
        boolean flag =false;
        if(consultBtn.isSelected())
        {
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"Please enter the ID to delete","Empty Field",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                for(int i =0;i<MaxDesigns.getInstance().getCon().size();i++)
                {
                    if(MaxDesigns.getInstance().getCon().get(i).getId().equals(text))
                    {
                        flag = true;
                        MaxDesigns.getInstance().getCon().get(i).setComplete();
                        MaxDesigns.getInstance().getCon().get(i).setUshare();
                        MaxDesigns.getInstance().getCon().get(i).setJshare();
                        JOptionPane.showMessageDialog(this,"Updation done","Congratulaion !!!!",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().SeperateCon(MaxDesigns.getInstance().getCon().get(i).getName(),FullData());
                        MaxDesigns.getInstance().ConWrite(fileData(i,1));
                        MaxDesigns.getInstance().writeCon();
                        break;
                    }
                    else
                        flag = false;
                }
                if(flag==false)
                    JOptionPane.showMessageDialog(this,"ID not Found","Error 🎃",JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(drawBtn.isSelected())
        {
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"Please enter the ID to delete","Empty Field",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                for(int i =0;i<MaxDesigns.getInstance().getDes().size();i++)
                {
                    if(MaxDesigns.getInstance().getDes().get(i).getId().equals(text))
                    {
                        flag = true;
                        MaxDesigns.getInstance().getDes().get(i).setComplete();
                        JOptionPane.showMessageDialog(this,"Updation done","Congratulaion !!!!",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().SeperateDraw(MaxDesigns.getInstance().getDes().get(i).getName(),FullData());
                        MaxDesigns.getInstance().DrawWrite(fileData(i,1));
                        MaxDesigns.getInstance().writeDes();
                        break;
                    }
                    else
                        flag = false;
                }
                if(flag==false)
                    JOptionPane.showMessageDialog(this,"ID not Found","Error 🎃",JOptionPane.ERROR_MESSAGE);
            }
        }  
        else
            JOptionPane.showMessageDialog(this,"You need to choose which type of project you want to delete","Type not chosen",JOptionPane.ERROR_MESSAGE);
              
        if(flag = false)
            JOptionPane.showMessageDialog(this,"ID does not seem to be present in our Data","ID not found",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_subBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton consultBtn;
    private javax.swing.JRadioButton drawBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
