/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEll
 */
public class DeleteVendor extends javax.swing.JInternalFrame {

    String text = "";
    
    /**
     * Creates new form DeleteVendor
     */
    public DeleteVendor() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        tableSet();
        setDataToRow();
        
        srTxt.setEnabled(false);
        idTxt.setEnabled(false);
        nameTxt.setEnabled(false);
    }
    
    public void setDataToRow()
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object rowData[]=new Object[4];
        model.setRowCount(0);
        if(MaxDesigns.getInstance().getVen().size()>0)
        {
            for(int i =0;i<MaxDesigns.getInstance().getVen().size();i++)
            {
                rowData[0]=i;
                rowData[1]=MaxDesigns.getInstance().getVen().get(i).getId();
                rowData[2]=MaxDesigns.getInstance().getVen().get(i).getCompany();
                rowData[3]=MaxDesigns.getInstance().getVen().get(i).getBalance();
                model.addRow(rowData);

            }
        }
    }
    
    public void tableSet()
    {
        jScrollPane1.setBackground(new Color(0,0,0,0));
       jScrollPane1.setOpaque(false);
       jTable1.setOpaque(false);
       ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
       jScrollPane1.getViewport().setOpaque(false);
    }
    
    
    public String fileData(int index, String text)
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               Delete VENDOR\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Umair Umar | Administrator\n\n";
               s += "Deleted Account Details................................... \n\n";
               s += "Vendor Name : "+MaxDesigns.getInstance().getVen().get(index).getCompany()+" ( "+MaxDesigns.getInstance().getVen().get(index).getId()+" )\n";
               s += "Owner Name : "+MaxDesigns.getInstance().getVen().get(index).getOwner()+"\n";
               s += "Balance : "+MaxDesigns.getInstance().getVen().get(index).getBalance()+"\n\n\n";
               s += "Deleted by Option : "+text+"\n";
               s += "                                                 MAX DESIGNS\n";
               s += "__________________________________________________________________________________________\n";
               return s;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        srBtn = new javax.swing.JRadioButton();
        srTxt = new javax.swing.JTextField();
        idBtn = new javax.swing.JRadioButton();
        idTxt = new javax.swing.JTextField();
        nameBtn = new javax.swing.JRadioButton();
        nameTxt = new javax.swing.JTextField();
        delBtn = new com.k33ptoo.components.KButton();

        setPreferredSize(new java.awt.Dimension(920, 787));

        kGradientPanel1.setkEndColor(new java.awt.Color(24, 24, 24));
        kGradientPanel1.setkStartColor(new java.awt.Color(186, 139, 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Delete Vendor");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jTable1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "ID", "Company Name", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setRowHeight(24);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Delete Details");

        buttonGroup1.add(srBtn);
        srBtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        srBtn.setForeground(new java.awt.Color(153, 0, 0));
        srBtn.setText("Delete By Sr. No.");
        srBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srBtnActionPerformed(evt);
            }
        });

        srTxt.setBackground(new java.awt.Color(240, 240, 240));
        srTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        srTxt.setForeground(new java.awt.Color(51, 0, 51));
        srTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        buttonGroup1.add(idBtn);
        idBtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        idBtn.setForeground(new java.awt.Color(153, 0, 0));
        idBtn.setText("Delete By ID");
        idBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBtnActionPerformed(evt);
            }
        });

        idTxt.setBackground(new java.awt.Color(240, 240, 240));
        idTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        idTxt.setForeground(new java.awt.Color(51, 0, 51));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        buttonGroup1.add(nameBtn);
        nameBtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        nameBtn.setForeground(new java.awt.Color(153, 0, 0));
        nameBtn.setText("Delete By Name");
        nameBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBtnActionPerformed(evt);
            }
        });

        nameTxt.setBackground(new java.awt.Color(240, 240, 240));
        nameTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(51, 0, 51));
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(idBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(srTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(srBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(nameBtn)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(srBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(srTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(idBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(nameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        delBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        delBtn.setText("DELETE");
        delBtn.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        delBtn.setkEndColor(new java.awt.Color(24, 24, 24));
        delBtn.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        delBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        delBtn.setkHoverStartColor(new java.awt.Color(0, 0, 153));
        delBtn.setkStartColor(new java.awt.Color(186, 139, 2));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srBtnActionPerformed
        // TODO add your handling code here:
        if(srBtn.isSelected())
        {
            srTxt.setText(null);
            idTxt.setText(null);
            nameTxt.setText(null);
            srTxt.setEnabled(true);
            idTxt.setEnabled(false);
            nameTxt.setEnabled(false);
        }
    }//GEN-LAST:event_srBtnActionPerformed

    private void idBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBtnActionPerformed
        // TODO add your handling code here:
        if(idBtn.isSelected())
        {
            srTxt.setText(null);
            idTxt.setText(null);
            nameTxt.setText(null);
            srTxt.setEnabled(false);
            idTxt.setEnabled(true);
            nameTxt.setEnabled(false);
        }
    }//GEN-LAST:event_idBtnActionPerformed

    private void nameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBtnActionPerformed
        // TODO add your handling code here:
        if(nameBtn.isSelected())
        {
            srTxt.setText(null);
            idTxt.setText(null);
            nameTxt.setText(null);
            srTxt.setEnabled(false);
            idTxt.setEnabled(false);
            nameTxt.setEnabled(true);
        }
    }//GEN-LAST:event_nameBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        if(srBtn.isSelected())
        {
            text = srTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The Serial Number Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                if(MaxDesigns.getInstance().getVen().get(0).isDigits(text))
                {
                    if(Integer.parseInt(text)<MaxDesigns.getInstance().getVen().size())
                    {
                        MaxDesigns.getInstance().VenWrite(fileData(Integer.parseInt(text),"By Serial Number"));
                        MaxDesigns.getInstance().getVen().remove(Integer.parseInt(text));
                        JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().writeVen();
                        setDataToRow();
                    }
                    else
                        JOptionPane.showMessageDialog(this,"Sr No. Not in range","Error !",JOptionPane.ERROR_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(this,"The Serial Number should be a digit","Invalid Input",JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(idBtn.isSelected())
        {
            text = idTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The ID Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            { 
                int index = -1;
                for(int i =0;i<MaxDesigns.getInstance().getVen().size();i++)
                {
                    if(MaxDesigns.getInstance().getVen().get(i).getId().equals(text))
                    {
                        index = i;
                        break;
                    }
                    else
                        index = -1;
                }
                if(index==-1)
                {
                    JOptionPane.showMessageDialog(this,"ID does not seem to match the data","ID not found",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                        MaxDesigns.getInstance().VenWrite(fileData(index,"By ID"));
                        MaxDesigns.getInstance().getVen().remove(index);
                        JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().writeVen();
                        setDataToRow();
                }
            }
        }
        else if(nameBtn.isSelected())
        {
            text = nameTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The Name Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                int index = -1;
                for(int i =0;i<MaxDesigns.getInstance().getVen().size();i++)
                {
                    if(MaxDesigns.getInstance().getVen().get(i).getCompany().equals(text))
                    {
                        index = i;
                        break;
                    }
                    else
                        index = -1;
                }
                if(index==-1)
                {
                    JOptionPane.showMessageDialog(this,"Name does not seem to match the data","Name not found",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                        MaxDesigns.getInstance().VenWrite(fileData(index,"By Name"));
                        MaxDesigns.getInstance().getVen().remove(index);
                        JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().writeVen();
                        setDataToRow();
                }
            }
        }
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.k33ptoo.components.KButton delBtn;
    private javax.swing.JRadioButton idBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JRadioButton nameBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JRadioButton srBtn;
    private javax.swing.JTextField srTxt;
    // End of variables declaration//GEN-END:variables
}
