/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author DEll
 */
public class DeleteDProject extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteDProject
     */
    public DeleteDProject() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        ownerTxt.setEnabled(false);
        idTxt.setEnabled(false);
        nameTxt.setEnabled(false);
    }
    
    public String fileData(int index, String text)
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               Delete Project\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Ayesha | Accountant\n\n";
               s += "Deleted Account Details................................... \n\n";
               s += "Project Name : "+MaxDesigns.getInstance().getDes().get(index).getName()+" ( "+MaxDesigns.getInstance().getDes().get(index).getId()+" )\n";
               s += "Status : "+MaxDesigns.getInstance().getDes().get(index).getStatus()+"\n";
               s += "Services : "+MaxDesigns.getInstance().getDes().get(index).getServices()+"\n";
               s += "Balance : "+MaxDesigns.getInstance().getDes().get(index).getBalance()+"\n\n\n";
               s += "Deleted by Option : "+text+"\n";
               s += "                                                 MAX DESIGNS\n";
               s += "__________________________________________________________________________________________\n";
               return s;
    }
    
    
    public String FullData()
    {
        String data = "\n_______________________________________________________________________________________\n\n";
        data += "                  This Project has been Deleted";
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now(); 
        data += "Date/Time : "+dtf.format(now)+"               MAX DESIGNS\n";
        data += "_______________________________________________________________________________________\n\n";
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        owner = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ownerBtn = new javax.swing.JRadioButton();
        ownerTxt = new javax.swing.JTextField();
        idBtn = new javax.swing.JRadioButton();
        idTxt = new javax.swing.JTextField();
        nameBtn = new javax.swing.JRadioButton();
        nameTxt = new javax.swing.JTextField();
        delBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 728));

        owner.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Delete Projects");

        ownerBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(ownerBtn);
        ownerBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        ownerBtn.setForeground(new java.awt.Color(153, 0, 0));
        ownerBtn.setText("Delete By Owner Name :");
        ownerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ownerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerBtnActionPerformed(evt);
            }
        });

        ownerTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ownerTxt.setForeground(new java.awt.Color(51, 0, 51));
        ownerTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        idBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(idBtn);
        idBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        idBtn.setForeground(new java.awt.Color(153, 0, 0));
        idBtn.setText("Delete By ID");
        idBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBtnActionPerformed(evt);
            }
        });

        idTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        idTxt.setForeground(new java.awt.Color(51, 0, 51));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        nameBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(nameBtn);
        nameBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        nameBtn.setForeground(new java.awt.Color(153, 0, 0));
        nameBtn.setText("Delete By Name");
        nameBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBtnActionPerformed(evt);
            }
        });

        nameTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(51, 0, 51));
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        delBtn.setBackground(new java.awt.Color(0, 0, 0));
        delBtn.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        delBtn.setForeground(new java.awt.Color(255, 255, 255));
        delBtn.setText("DELETE");
        delBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 3));
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ownerLayout = new javax.swing.GroupLayout(owner);
        owner.setLayout(ownerLayout);
        ownerLayout.setHorizontalGroup(
            ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownerLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ownerLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idBtn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownerBtn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameBtn, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ownerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ownerLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        ownerLayout.setVerticalGroup(
            ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ownerLayout.createSequentialGroup()
                .addGroup(ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(ownerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ownerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(idBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(nameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(owner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(owner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ownerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerBtnActionPerformed
        // TODO add your handling code here:
        if(ownerBtn.isSelected())
        {
            ownerTxt.setText("");
            idTxt.setText("");
            nameTxt.setText("");
            ownerTxt.setEnabled(true);
            idTxt.setEnabled(false);
            nameTxt.setEnabled(false);
        }
    }//GEN-LAST:event_ownerBtnActionPerformed

    private void idBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBtnActionPerformed
        // TODO add your handling code here:
        if(idBtn.isSelected())
        {
            ownerTxt.setText("");
            idTxt.setText("");
            nameTxt.setText("");
            ownerTxt.setEnabled(false);
            idTxt.setEnabled(true);
            nameTxt.setEnabled(false);
        }
    }//GEN-LAST:event_idBtnActionPerformed

    private void nameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBtnActionPerformed
        // TODO add your handling code here:
        if(nameBtn.isSelected())
        {
            ownerTxt.setText("");
            idTxt.setText("");
            nameTxt.setText("");
            ownerTxt.setEnabled(false);
            idTxt.setEnabled(false);
            nameTxt.setEnabled(true);
        }
    }//GEN-LAST:event_nameBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:\
        String text = "";
        if(ownerBtn.isSelected())
        {
            text = ownerTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The Owner Name Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                int index = -1;
                for(int i = 0;i<MaxDesigns.getInstance().getDes().size();i++)
                {
                    if(MaxDesigns.getInstance().getDes().get(i).getOwner().equals(text))
                    {
                        index  = i;
                        break;
                    }
                    else
                        index  = -1;
                }
                if(index == -1)
                {
                    JOptionPane.showMessageDialog(this,"The Owner Name Not Found","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    MaxDesigns.getInstance().DrawWrite(fileData(index,"By Owner Name"));
                    MaxDesigns.getInstance().SeperateDraw(MaxDesigns.getInstance().getDes().get(index).getName(),FullData());
                    MaxDesigns.getInstance().getDes().remove(index);
                    JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                    MaxDesigns.getInstance().writeDes();
                }
            }
        }
        else if(idBtn.isSelected())
        {
            text = idTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The ID Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                int index = -1;
                for(int i = 0;i<MaxDesigns.getInstance().getDes().size();i++)
                {
                    if(MaxDesigns.getInstance().getDes().get(i).getId().equals(text))
                    {
                        index  = i;
                        break;
                    }
                    else
                        index  = -1;
                }
                if(index == -1)
                {
                    JOptionPane.showMessageDialog(this,"The ID Not Found","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    MaxDesigns.getInstance().DrawWrite(fileData(index,"By ID"));
                    MaxDesigns.getInstance().SeperateDraw(MaxDesigns.getInstance().getDes().get(index).getName(),FullData());
                    MaxDesigns.getInstance().getDes().remove(index);
                    JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                    MaxDesigns.getInstance().writeDes();
                }
            }
        }
        else if(nameBtn.isSelected())
        {
            text = nameTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The Name Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                int index = -1;
                for(int i = 0;i<MaxDesigns.getInstance().getDes().size();i++)
                {
                    if(MaxDesigns.getInstance().getDes().get(i).getName().equals(text))
                    {
                        index  = i;
                        break;
                    }
                    else
                        index  = -1;
                }
                if(index == -1)
                {
                    JOptionPane.showMessageDialog(this,"The Project Name Not Found","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    MaxDesigns.getInstance().DrawWrite(fileData(index,"By Project Name"));
                    MaxDesigns.getInstance().SeperateDraw(MaxDesigns.getInstance().getDes().get(index).getName(),FullData());
                    MaxDesigns.getInstance().getDes().remove(index);
                    JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                    MaxDesigns.getInstance().writeDes();
                }
            }
        }
        else
            JOptionPane.showMessageDialog(this,"You First need to choose on of the Delete Types by clicking on radio buttons","Radio Button Not Selected",JOptionPane.ERROR_MESSAGE);
            
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delBtn;
    private javax.swing.JRadioButton idBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton nameBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPanel owner;
    private javax.swing.JRadioButton ownerBtn;
    private javax.swing.JTextField ownerTxt;
    // End of variables declaration//GEN-END:variables
}
