/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEll
 */
public class DeleteWorker extends javax.swing.JInternalFrame {

    String text = "";
    
    /**
     * Creates new form DeleteWorker
     */
    public DeleteWorker() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        srTxt.setEnabled(false);
        nameTxt.setEnabled(false);
        idTxt.setEnabled(false);
        
        tableSet();
        setDataToRow();
    }
    
  public void setDataToRow()
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object rowData[]=new Object[4];
        model.setRowCount(0);
        if(MaxDesigns.getInstance().getEmp().size()>0)
        {
            for(int i =0;i<MaxDesigns.getInstance().getEmp().size();i++)
            {
                rowData[0]=i;
                rowData[1]=MaxDesigns.getInstance().getEmp().get(i).getName();
                rowData[2]=MaxDesigns.getInstance().getEmp().get(i).getID();
                rowData[3]=MaxDesigns.getInstance().getEmp().get(i).getStatus();
                model.addRow(rowData);

            }
        }
    }
    
    public String fileData(int index, String text)
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               Delete WORKER\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Ayesha | Accountant\n\n";
               s += "Deleted Account Details................................... \n\n";
               s += "Employee Name : "+MaxDesigns.getInstance().getEmp().get(index).getName()+" ( "+MaxDesigns.getInstance().getEmp().get(index).getID()+" )\n";
               s += "Status : "+MaxDesigns.getInstance().getEmp().get(index).getStatus()+"\n";
               s += "Salary : "+MaxDesigns.getInstance().getEmp().get(index).getSalary()+"\n\n\n";
               s += "Deleted by Option : "+text+"\n";
               s += "                                                 MAX DESIGNS\n";
               s += "__________________________________________________________________________________________\n";
               return s;
    }
    
    public void tableSet()
    {
        jScrollPane1.setBackground(new Color(0,0,0,0));
       jScrollPane1.setOpaque(false);
       jTable1.setOpaque(false);
       ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
       jScrollPane1.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        srBtn = new javax.swing.JRadioButton();
        srTxt = new javax.swing.JTextField();
        nameBtn = new javax.swing.JRadioButton();
        nameTxt = new javax.swing.JTextField();
        idBtn = new javax.swing.JRadioButton();
        idTxt = new javax.swing.JTextField();
        delBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 738));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Delete Employee");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr no.", "Name", "ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setRowHeight(30);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        srBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(srBtn);
        srBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        srBtn.setForeground(new java.awt.Color(153, 0, 0));
        srBtn.setText("By Serial Number :");
        srBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srBtnActionPerformed(evt);
            }
        });

        srTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        srTxt.setForeground(new java.awt.Color(51, 0, 51));
        srTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));

        nameBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(nameBtn);
        nameBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nameBtn.setForeground(new java.awt.Color(153, 0, 0));
        nameBtn.setText("By Name :");
        nameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBtnActionPerformed(evt);
            }
        });

        nameTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(51, 0, 51));
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));

        idBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(idBtn);
        idBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        idBtn.setForeground(new java.awt.Color(153, 0, 0));
        idBtn.setText("By ID :");
        idBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBtnActionPerformed(evt);
            }
        });

        idTxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        idTxt.setForeground(new java.awt.Color(51, 0, 51));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));

        delBtn.setBackground(new java.awt.Color(51, 0, 51));
        delBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        delBtn.setForeground(new java.awt.Color(255, 255, 255));
        delBtn.setText("DELETE");
        delBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameBtn)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(212, 212, 212)
                                    .addComponent(srBtn))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(221, 221, 221)
                                    .addComponent(srTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idBtn)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(srBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(srTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(nameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srBtnActionPerformed
        // TODO add your handling code here:
        if(srBtn.isSelected())
        {
            srTxt.setText(null);
            idTxt.setText(null);
            nameTxt.setText(null);
            srTxt.setEnabled(true);
            idTxt.setEnabled(false);
            nameTxt.setEnabled(false);
        }
    }//GEN-LAST:event_srBtnActionPerformed

    private void nameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBtnActionPerformed
        // TODO add your handling code here:
        if(nameBtn.isSelected())
        {
            srTxt.setText(null);
            idTxt.setText(null);
            nameTxt.setText(null);
            srTxt.setEnabled(false);
            idTxt.setEnabled(false);
            nameTxt.setEnabled(true);
        }
    }//GEN-LAST:event_nameBtnActionPerformed

    private void idBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBtnActionPerformed
        // TODO add your handling code here:
        if(idBtn.isSelected())
        {
            srTxt.setText(null);
            idTxt.setText(null);
            nameTxt.setText(null);
            srTxt.setEnabled(false);
            idTxt.setEnabled(true);
            nameTxt.setEnabled(false);
        }
    }//GEN-LAST:event_idBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        if(srBtn.isSelected())
        {
            text = srTxt.getText();
             if(text.equals("") || text.equals(null))
             {
                 JOptionPane.showMessageDialog(this,"The Serial Number Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
             }
             else
            {
                if(MaxDesigns.getInstance().getEmp().get(0).isDigits(text))
                {
                    if(Integer.parseInt(text)<MaxDesigns.getInstance().getEmp().size())
                    {
                        MaxDesigns.getInstance().EmpWrite(fileData(Integer.parseInt(text),"By Serial Number"));
                        MaxDesigns.getInstance().getEmp().remove(Integer.parseInt(text));
                        JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().writeEmp();
                        setDataToRow();
                    }
                    else
                        JOptionPane.showMessageDialog(this,"Sr No. Not in range","Error !",JOptionPane.ERROR_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(this,"The Serial Number should be a digit","Invalid Input",JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(idBtn.isSelected())
        {
            text = idTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The ID Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            { 
                int index = -1;
                for(int i =0;i<MaxDesigns.getInstance().getEmp().size();i++)
                {
                    if(MaxDesigns.getInstance().getEmp().get(i).getID().equals(text))
                    {
                        index = i;
                        break;
                    }
                    else
                        index = -1;
                }
                if(index==-1)
                {
                    JOptionPane.showMessageDialog(this,"ID does not seem to match the data","ID not found",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                        MaxDesigns.getInstance().EmpWrite(fileData(index,"By ID"));
                        MaxDesigns.getInstance().getEmp().remove(index);
                        JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().writeEmp();
                        setDataToRow();
                }
            }
        }
        else if(nameBtn.isSelected())
        {
            text = nameTxt.getText();
            if(text.equals("") || text.equals(null))
            {
                JOptionPane.showMessageDialog(this,"The Name Input is empty","Empty Fields",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                int index = -1;
                for(int i =0;i<MaxDesigns.getInstance().getEmp().size();i++)
                {
                    if(MaxDesigns.getInstance().getEmp().get(i).getName().equals(text))
                    {
                        index = i;
                        break;
                    }
                    else
                        index = -1;
                }
                if(index==-1)
                {
                    JOptionPane.showMessageDialog(this,"Name does not seem to match the data","Name not found",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                        MaxDesigns.getInstance().EmpWrite(fileData(index,"By Name"));
                        MaxDesigns.getInstance().getEmp().remove(index);
                        JOptionPane.showMessageDialog(this,"The Data removed Succesfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                        MaxDesigns.getInstance().writeEmp();
                        setDataToRow();
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"You need to choose the type through which you want to delete data","Type not chosen",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delBtn;
    private javax.swing.JRadioButton idBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton nameBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JRadioButton srBtn;
    private javax.swing.JTextField srTxt;
    // End of variables declaration//GEN-END:variables
}
