/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author DEll
 */
public class DetailsDProject extends javax.swing.JInternalFrame {

    public int index = -1;
    
    public String data = "";
    
    /**
     * Creates new form DetailsDProject
     */
    public DetailsDProject() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        recBtn.setEnabled(false);
        amountTxt.setEnabled(false);
        detailTxt.setEnabled(false);
    }
    
    public String fileData()
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               Project Transaction\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Umair Umar | Administrator\n\n";
               s += "Project Name : "+MaxDesigns.getInstance().getDes().get(index).getName()+"\n";
               s += "Project ID : "+MaxDesigns.getInstance().getDes().get(index).getId()+"\n";
               s += "Project Amount Decided : "+ MaxDesigns.getInstance().getDes().get(index).getAmount()+"\n";
               s += "Balance Before Transaction : "+ MaxDesigns.getInstance().getDes().get(index).getBalance()+"\n";
               return s;
    }
    
    public String FullData()
    {
        String data = "\n_______________________________________________________________________________________\n\n";
               data += "                                      TRANSACTION\n";
               data += "_______________________________________________________________________________________\n";
               return data;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        srchBtn = new javax.swing.JButton();
        recBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        invalidAmount = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTxt = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(930, 766));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Detials & Transaction");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("ID :");

        idTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        idTxt.setForeground(new java.awt.Color(51, 0, 51));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        srchBtn.setBackground(new java.awt.Color(0, 0, 0));
        srchBtn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        srchBtn.setForeground(new java.awt.Color(255, 255, 255));
        srchBtn.setText("Search");
        srchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        srchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBtnActionPerformed(evt);
            }
        });

        recBtn.setBackground(new java.awt.Color(0, 0, 0));
        recBtn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        recBtn.setForeground(new java.awt.Color(255, 255, 255));
        recBtn.setText("Add to Records");
        recBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        recBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recBtnActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Amount :");

        amountTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        amountTxt.setForeground(new java.awt.Color(51, 0, 51));
        amountTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        invalidAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidAmount.setForeground(new java.awt.Color(153, 0, 0));
        invalidAmount.setText("(Amount should be greater than 0)");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("Details :");

        detailTxt.setColumns(20);
        detailTxt.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        detailTxt.setForeground(new java.awt.Color(51, 0, 51));
        detailTxt.setRows(5);
        detailTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jScrollPane1.setViewportView(detailTxt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(246, 246, 246)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(idTxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(138, 138, 138)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(srchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(recBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 148, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(invalidAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(270, 270, 270)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(srchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(recBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(invalidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBtnActionPerformed
        // TODO add your handling code here:
        
        String id = idTxt.getText();
        
        if(id.equals("") || id.equals(null))
        {
            JOptionPane.showMessageDialog(this,"You first need to search the Project for which\nthe data is to be added","Empty Input",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            for(int i = 0;i<MaxDesigns.getInstance().getDes().size();i++)
            {
                if(MaxDesigns.getInstance().getDes().get(i).getId().equals(id))
                {
                    
                    index = i;
                    this.data = fileData();
                    recBtn.setEnabled(true);
                    amountTxt.setEnabled(true);
                    detailTxt.setEnabled(true);
                    srchBtn.setEnabled(false);
                    idTxt.setEnabled(false);
                    break;
                }
                else
                    index = -1;
            }
            if(index == -1)
                JOptionPane.showMessageDialog(this,"The following Project Does not seem to present in our data\nTry again with something else","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_srchBtnActionPerformed

    private void recBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recBtnActionPerformed
        // TODO add your handling code here:
        String amount = amountTxt.getText();
        String details = detailTxt.getText();
        String fdata = FullData();
        if(amount.equals("") || amount.equals(null) || details.equals("") || details.equals(null))
        {
            if(amount.equals("") || amount.equals(null))
            {
                invalidAmount.setText("Empty Field");
            }
            else
                invalidAmount.setText("");
                
            
            if(details.equals("") || details.equals(null))
            {
                JOptionPane.showMessageDialog(this,"You need to enter the details of the Transaction","Empty field",JOptionPane.ERROR_MESSAGE);
            }
                
        }
        else
        {
            if(MaxDesigns.getInstance().getDes().get(index).isDigits(amount))
            {
                invalidAmount.setText("");
                data = fileData();
                int a = Integer.parseInt(amount);
//                System.out.print(a);
                fdata += "Amount Chequed : "+a+"\n";
                int b = MaxDesigns.getInstance().getDes().get(index).getBalance();
//                System.out.print(b);
                a = b-a;
//                System.out.print(a);
                MaxDesigns.getInstance().getDes().get(index).setBalance(a);
                
//                System.out.print(MaxDesigns.getInstance().getDes().get(index).getBalance());
                data += "Balance After Transaction will be : "+ MaxDesigns.getInstance().getDes().get(index).getBalance()+"\n\n";
                data += "The details of the Cheque Passed is as follows\n\n";
                data += details+"\n\n";
                fdata += "Details of the Transaction are as follows :\n\n";
                fdata += details +"\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
                fdata += "Date/Time : "+dtf.format(now)+"\n";
                fdata += "                                     MAX DESIGNS\n";
                fdata += "_______________________________________________________________________________________\n\n";
                data += "                                        MAX DESIGNS\n";
                data += "______________________________________________________________________________________________\n\n";
                MaxDesigns.getInstance().DrawWrite(data);
                MaxDesigns.getInstance().SeperateDraw(MaxDesigns.getInstance().getDes().get(index).getName(),fdata);
                MaxDesigns.getInstance().writeDes();
                JOptionPane.showMessageDialog(this,"Data has been Added Successfully","Congratulations :)",JOptionPane.INFORMATION_MESSAGE);
                
            }
            else
                invalidAmount.setText("Amount should be in digits (>0)");
        }
    }//GEN-LAST:event_recBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JTextArea detailTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel invalidAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton recBtn;
    private javax.swing.JButton srchBtn;
    // End of variables declaration//GEN-END:variables
}
