/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
public class EmployeeMenu extends javax.swing.JFrame {

    Color Focus ;
    Color Default;
    Color Clicked ;
    Color textC ;
    Color textD ;
    
    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu() {
        initComponents();
        Focus = new Color(101,116,140);
        Default = new Color(32,32,32);
        Clicked = new Color(255,255,255);
        textC = new Color(0,0,0);
        textD = new Color(255,255,255);
        
        dateLabel.setText(java.time.LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        workerDis = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        signOut = new javax.swing.JLabel();
        workerDel = new javax.swing.JLabel();
        workerUp = new javax.swing.JLabel();
        workerDrawing = new javax.swing.JLabel();
        workerConsult = new javax.swing.JLabel();
        workerComp = new javax.swing.JLabel();
        workerRec = new javax.swing.JLabel();
        workerAdd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Employee = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1183, 830));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Max Designs");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 110, 40));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 0, 51));
        dateLabel.setText("Date");
        jPanel1.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 170, 40));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-close-window-48.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ayesha | Max  Designs Employee");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 683, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel7.setText("Accountant");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-person-30.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 40, 40, 40));

        jPanel3.setBackground(new java.awt.Color(32, 32, 32));

        workerDis.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerDis.setForeground(new java.awt.Color(255, 255, 255));
        workerDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-show-sidepanel-50 (1).png"))); // NOI18N
        workerDis.setText("Display Worker");
        workerDis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerDis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerDisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerDisFocusLost(evt);
            }
        });
        workerDis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerDisMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-menu-30.png"))); // NOI18N
        jLabel11.setText(" Menu");

        signOut.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        signOut.setForeground(new java.awt.Color(255, 255, 255));
        signOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-sign-out-30.png"))); // NOI18N
        signOut.setText("Log Out");
        signOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signOutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signOutFocusLost(evt);
            }
        });
        signOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutMouseClicked(evt);
            }
        });

        workerDel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerDel.setForeground(new java.awt.Color(255, 255, 255));
        workerDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-delete-24.png"))); // NOI18N
        workerDel.setText("Delete Worker");
        workerDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerDel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerDelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerDelFocusLost(evt);
            }
        });
        workerDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerDelMouseClicked(evt);
            }
        });

        workerUp.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerUp.setForeground(new java.awt.Color(255, 255, 255));
        workerUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-update-24.png"))); // NOI18N
        workerUp.setText("Update Worker");
        workerUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                workerUpMouseDragged(evt);
            }
        });
        workerUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerUpFocusLost(evt);
            }
        });
        workerUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                workerUpMouseEntered(evt);
            }
        });

        workerDrawing.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerDrawing.setForeground(new java.awt.Color(255, 255, 255));
        workerDrawing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-design-30.png"))); // NOI18N
        workerDrawing.setText("Drawing Design Projects");
        workerDrawing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerDrawing.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerDrawingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerDrawingFocusLost(evt);
            }
        });
        workerDrawing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerDrawingMouseClicked(evt);
            }
        });

        workerConsult.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerConsult.setForeground(new java.awt.Color(255, 255, 255));
        workerConsult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-vastu-consultancy-50 (1).png"))); // NOI18N
        workerConsult.setText("Consultancy Projects");
        workerConsult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerConsult.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerConsultFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerConsultFocusLost(evt);
            }
        });
        workerConsult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerConsultMouseClicked(evt);
            }
        });

        workerComp.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerComp.setForeground(new java.awt.Color(255, 255, 255));
        workerComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/complete.png"))); // NOI18N
        workerComp.setText("Complete Projects");
        workerComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerComp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerCompFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerCompFocusLost(evt);
            }
        });
        workerComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerCompMouseClicked(evt);
            }
        });

        workerRec.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerRec.setForeground(new java.awt.Color(255, 255, 255));
        workerRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-transaction-24.png"))); // NOI18N
        workerRec.setText("Records");
        workerRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerRec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerRecFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerRecFocusLost(evt);
            }
        });
        workerRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerRecMouseClicked(evt);
            }
        });

        workerAdd.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        workerAdd.setForeground(new java.awt.Color(255, 255, 255));
        workerAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-add-24.png"))); // NOI18N
        workerAdd.setText(" Add Worker");
        workerAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        workerAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workerAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workerAddFocusLost(evt);
            }
        });
        workerAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                workerAddMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11))
            .addComponent(workerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(workerDel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(workerUp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(workerDis, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(workerDrawing, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(workerConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(workerComp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(workerRec, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(signOut, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(workerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(workerDel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(workerUp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(workerDis, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(workerDrawing, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(workerConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(workerComp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(workerRec, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addComponent(signOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 790));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel3.setText("Team by : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 100, 40));

        Employee.setBackground(new java.awt.Color(255, 255, 255));
        Employee.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(255, 153, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/Logo (1).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("GothicI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("<html>\nHelping you to Build Better\n<br>\nFrom Concept to Completion ");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("Home Screen");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        Employee.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EmployeeLayout = new javax.swing.GroupLayout(Employee);
        Employee.setLayout(EmployeeLayout);
        EmployeeLayout.setHorizontalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EmployeeLayout.setVerticalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 930, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 830));

        setSize(new java.awt.Dimension(1178, 830));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        MaxDesigns.getInstance().writeEmp();
        MaxDesigns.getInstance().writeDes();
        MaxDesigns.getInstance().writeCon();
        MaxDesigns.getInstance().writeVen();
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void signOutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signOutFocusGained
        // TODO add your handling code here:
        signOut.setBackground(Focus);
    }//GEN-LAST:event_signOutFocusGained

    private void signOutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signOutFocusLost
        // TODO add your handling code here:
        signOut.setBackground(this.Default);
    }//GEN-LAST:event_signOutFocusLost

    private void workerDisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerDisFocusGained
        // TODO add your handling code here:
        workerDis.setBackground(Focus);
    }//GEN-LAST:event_workerDisFocusGained

    private void workerDisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerDisFocusLost
        // TODO add your handling code here:
         workerDis.setBackground(this.Default);
    }//GEN-LAST:event_workerDisFocusLost

    private void workerDelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerDelFocusGained
        // TODO add your handling code here:
        workerDel.setBackground(Focus);
    }//GEN-LAST:event_workerDelFocusGained

    private void workerDelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerDelFocusLost
        // TODO add your handling code here:
        workerDel.setBackground(this.Default);
    }//GEN-LAST:event_workerDelFocusLost

    private void workerUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerUpFocusGained
        // TODO add your handling code here:
        workerUp.setBackground(Focus);
    }//GEN-LAST:event_workerUpFocusGained

    private void workerUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerUpFocusLost
        // TODO add your handling code here:
        workerUp.setBackground(this.Default);
    }//GEN-LAST:event_workerUpFocusLost

    private void workerDrawingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerDrawingFocusGained
        // TODO add your handling code here:
        workerDrawing.setBackground(Focus);
    }//GEN-LAST:event_workerDrawingFocusGained

    private void workerDrawingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerDrawingFocusLost
        // TODO add your handling code here:
        workerDrawing.setBackground(this.Default);
    }//GEN-LAST:event_workerDrawingFocusLost

    private void workerConsultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerConsultFocusGained
        // TODO add your handling code here:
        workerConsult.setBackground(Focus);
    }//GEN-LAST:event_workerConsultFocusGained

    private void workerConsultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerConsultFocusLost
        // TODO add your handling code here:
        workerConsult.setBackground(this.Default);
    }//GEN-LAST:event_workerConsultFocusLost

    private void workerCompFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerCompFocusGained
        // TODO add your handling code here:
        workerComp.setBackground(Focus);
    }//GEN-LAST:event_workerCompFocusGained

    private void workerCompFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerCompFocusLost
        // TODO add your handling code here:
        workerComp.setBackground(this.Default);
    }//GEN-LAST:event_workerCompFocusLost

    private void workerRecFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerRecFocusGained
        // TODO add your handling code here:
        workerRec.setBackground(Focus);
    }//GEN-LAST:event_workerRecFocusGained

    private void workerRecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerRecFocusLost
        // TODO add your handling code here:
        workerRec.setBackground(this.Default);
    }//GEN-LAST:event_workerRecFocusLost

    private void workerAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerAddFocusGained
        // TODO add your handling code here:
        workerAdd.setBackground(new Color(101,116,140));
    }//GEN-LAST:event_workerAddFocusGained

    private void workerAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workerAddFocusLost
        // TODO add your handling code here:
        workerAdd.setBackground(this.Default);
    }//GEN-LAST:event_workerAddFocusLost

    private void workerUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerUpMouseEntered
        // TODO add your handling code here:
        workerAdd.setBackground(Focus);
    }//GEN-LAST:event_workerUpMouseEntered

    private void workerUpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerUpMouseDragged
        // TODO add your handling code here:
        workerAdd.setBackground(Focus);
    }//GEN-LAST:event_workerUpMouseDragged

    private void workerAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerAddMouseEntered
        // TODO add your handling code here:
        workerAdd.setBackground(Focus);
    }//GEN-LAST:event_workerAddMouseEntered

    private void workerAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerAddMouseClicked
        // TODO add your handling code here:
        Employee.removeAll();
        AddWorker a = new AddWorker();
        Employee.add(a).setVisible(true);
    }//GEN-LAST:event_workerAddMouseClicked

    private void workerDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerDelMouseClicked
        // TODO add your handling code here:
        Employee.removeAll();
        DeleteWorker a = new DeleteWorker();
        Employee.add(a).setVisible(true);
    }//GEN-LAST:event_workerDelMouseClicked

    private void workerUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerUpMouseClicked
        // TODO add your handling code here:
        Employee.removeAll();
        UpdateWorker a = new UpdateWorker();
        Employee.add(a).setVisible(true);
    }//GEN-LAST:event_workerUpMouseClicked

    private void workerDisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerDisMouseClicked
        // TODO add your handling code here:
        Employee.removeAll();
        DisplayWorkers a = new DisplayWorkers();
        Employee.add(a).setVisible(true);
    }//GEN-LAST:event_workerDisMouseClicked

    private void workerDrawingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerDrawingMouseClicked
        // TODO add your handling code here:
        DrawingDesign d = new DrawingDesign();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_workerDrawingMouseClicked

    private void workerConsultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerConsultMouseClicked
        // TODO add your handling code here:
        EmpConsultancy d = new EmpConsultancy();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_workerConsultMouseClicked

    private void workerCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerCompMouseClicked
        // TODO add your handling code here:
        Employee.removeAll();
        CompleteProjects a = new CompleteProjects();
        Employee.add(a).setVisible(true);
    }//GEN-LAST:event_workerCompMouseClicked

    private void workerRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerRecMouseClicked
        // TODO add your handling code here:
        Employee.removeAll();
        EmployeeRecordsForm a = new EmployeeRecordsForm();
        Employee.add(a).setVisible(true);
    }//GEN-LAST:event_workerRecMouseClicked

    private void signOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseClicked
        // TODO add your handling code here:
        EmployeeLogout a = new EmployeeLogout(this);
        a.setVisible(true);
        
    }//GEN-LAST:event_signOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Employee;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel signOut;
    private javax.swing.JLabel workerAdd;
    private javax.swing.JLabel workerComp;
    private javax.swing.JLabel workerConsult;
    private javax.swing.JLabel workerDel;
    private javax.swing.JLabel workerDis;
    private javax.swing.JLabel workerDrawing;
    private javax.swing.JLabel workerRec;
    private javax.swing.JLabel workerUp;
    // End of variables declaration//GEN-END:variables
}
