/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author DEll
 */
public class UpdateCProject extends javax.swing.JInternalFrame {

    int index = -1;
    String text = "";
    
    /**
     * Creates new form UpdateCProject
     */
    public UpdateCProject() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        upBtn.setEnabled(false);
        nameTxt.setEnabled(false);
        ownerTxt.setEnabled(false);
        cnicTxt.setEnabled(false);
        contactTxt.setEnabled(false);
        amountTxt.setEnabled(false);
        idTxt.setEnabled(true);
        srchBtn.setEnabled(true);
    }
    
    public String fileData(int index)
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               UPDATE PROJECT\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Ayesha | Accountant\n\n";
               s += "Account Details to be Updated. .................................. \n\n";
               s += "Name : "+MaxDesigns.getInstance().getCon().get(index).getName()+" ( "+MaxDesigns.getInstance().getCon().get(index).getId()+" )\n";
               s += "Status : "+MaxDesigns.getInstance().getCon().get(index).getStatus()+"\n";
               s += "Balance : "+MaxDesigns.getInstance().getCon().get(index).getBalance()+"\n\n\n";
               s += "                                                 MAX DESIGNS\n";
               s += "__________________________________________________________________________________________\n";
               return s;
    }
    
    public String FullData(){
        String data = "\n_______________________________________________________________________________________\n\n";
        data += "The following content has been updated :\n";
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        srchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        invalidName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ownerTxt = new javax.swing.JTextField();
        invalidOwner = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        invalidContact = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cnicTxt = new javax.swing.JTextField();
        invalidCnic = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        invalidAmount = new javax.swing.JLabel();
        upBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 766));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Update Projects");

        idTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        idTxt.setForeground(new java.awt.Color(51, 0, 51));
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("ID :");

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));

        srchBtn.setBackground(new java.awt.Color(0, 0, 0));
        srchBtn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        srchBtn.setForeground(new java.awt.Color(255, 255, 255));
        srchBtn.setText("Search");
        srchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        srchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Name  :");

        nameTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(51, 0, 51));
        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        invalidName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidName.setForeground(new java.awt.Color(153, 0, 0));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Owner Name :");

        ownerTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        ownerTxt.setForeground(new java.awt.Color(51, 0, 51));
        ownerTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        invalidOwner.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidOwner.setForeground(new java.awt.Color(153, 0, 0));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Owner Contact :");

        contactTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        contactTxt.setForeground(new java.awt.Color(51, 0, 51));
        contactTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        invalidContact.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidContact.setForeground(new java.awt.Color(153, 0, 0));
        invalidContact.setText("(Only digits required)");
        invalidContact.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Owner CNIC :");

        cnicTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        cnicTxt.setForeground(new java.awt.Color(51, 0, 51));
        cnicTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        invalidCnic.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidCnic.setForeground(new java.awt.Color(153, 0, 0));
        invalidCnic.setText("(Only digits required)");
        invalidCnic.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Amount :");

        amountTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        amountTxt.setForeground(new java.awt.Color(51, 0, 51));
        amountTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        invalidAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invalidAmount.setForeground(new java.awt.Color(153, 0, 0));
        invalidAmount.setText("(Amount should be greater than 0)");

        upBtn.setBackground(new java.awt.Color(0, 0, 0));
        upBtn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        upBtn.setForeground(new java.awt.Color(255, 255, 255));
        upBtn.setText("Update");
        upBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        upBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(212, 212, 212)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(srchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(invalidName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(ownerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(invalidOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(cnicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(invalidCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(invalidContact, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(20, 20, 20)
                                    .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(invalidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(212, 212, 212))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(invalidName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(invalidOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(invalidCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(invalidContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(invalidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBtnActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<MaxDesigns.getInstance().getCon().size();i++)
        {
            if(MaxDesigns.getInstance().getCon().get(i).getId().equals(idTxt.getText()))
            {
                index = i;
                this.text = fileData(i);
                break;
            }
            else
                index = -1;
        }
        if(index  == -1)
        {
            JOptionPane.showMessageDialog(this,"The ID not Found","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            upBtn.setEnabled(true);
            nameTxt.setEnabled(true);
            ownerTxt.setEnabled(true);
            cnicTxt.setEnabled(true);
            contactTxt.setEnabled(true);
            amountTxt.setEnabled(true);
            idTxt.setEnabled(false);
            srchBtn.setEnabled(false);
            
            nameTxt.setText(MaxDesigns.getInstance().getCon().get(index).getName());
            ownerTxt.setText(MaxDesigns.getInstance().getCon().get(index).getOwner());
            cnicTxt.setText(MaxDesigns.getInstance().getCon().get(index).getCnic());
            contactTxt.setText(MaxDesigns.getInstance().getCon().get(index).getContact());
            amountTxt.setText(MaxDesigns.getInstance().getCon().get(index).getAmount()+"");
        }
    }//GEN-LAST:event_srchBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        // TODO add your handling code here:
        MaxDesigns.getInstance().ConWrite(text);
        String a = "";
        String data = FullData();
        String n = MaxDesigns.getInstance().getCon().get(index).getName();
        if(nameTxt.getText().equals("") || nameTxt.getText().equals(null))
        {}
        else
        {
            if(MaxDesigns.getInstance().getCon().get(index).setName(nameTxt.getText()))
            {
                invalidName.setText("");
                data += "Name : "+nameTxt.getText()+"\n";
                data += "The Rest of the Details regarding this project will be saved in \""+nameTxt.getText()+".txt\" file\n";
            }
            else
            {
                invalidName.setText("Invalid Name");
                a = "1";
            }
        }
        
        if(ownerTxt.getText().equals("") || ownerTxt.getText().equals(null))
        {}
        else
        {
            if(MaxDesigns.getInstance().getCon().get(index).setOwner(ownerTxt.getText()))
            {
                invalidOwner.setText("");
                data += "Owner Name : "+ownerTxt.getText()+"\n";
            }
            else
            {
                invalidName.setText("Invalid Owner Name");
                a = "1";
            }
        }
        
        if(cnicTxt.getText().equals("") || cnicTxt.getText().equals(null))
        {}
        else
        {
            if(MaxDesigns.getInstance().getCon().get(index).setCnic(cnicTxt.getText()))
            {
                invalidCnic.setText("");
                data += "Owner CNIC : "+cnicTxt.getText()+"\n";
            }
            else
            {
                invalidCnic.setText("Invalid CNIC");
                a = "1";
            }
        }
        
        if(contactTxt.getText().equals("") || contactTxt.getText().equals(null))
        {}
        else
        {
            if(MaxDesigns.getInstance().getCon().get(index).setContact(contactTxt.getText()))
            {
                invalidContact.setText("");
                data += "Contact of Owner : "+contactTxt.getText()+"\n";
            }
            else
            {
                invalidContact.setText("Invalid Contact Number");
                a = "1";
            }
        }
        
        if(amountTxt.getText().equals("") || amountTxt.getText().equals(null))
        {}
        else
        {
            if(MaxDesigns.getInstance().getCon().get(index).isDigits(amountTxt.getText()))
            {
                invalidAmount.setText("");
                int c = Integer.parseInt(amountTxt.getText());
                int d = MaxDesigns.getInstance().getCon().get(index).getAmount();
                int amount = -1;
                if(c>d)
                    amount = c-d;
                else if(d>=c)
                    amount = d-c;
                if(MaxDesigns.getInstance().getCon().get(index).setAmount(c))
                {
                    invalidAmount.setText("");
                    MaxDesigns.getInstance().getCon().get(index).setBalance(MaxDesigns.getInstance().getCon().get(index).getBalance()+amount);
                    data += "Amount : "+c+"\n";
                }
                else
                {
                    invalidAmount.setText("It should be greater than 0");
                    a = "1";
                }
            }
            else
            {
                invalidAmount.setText("It can be digits only");
                a = "1";
            } 
        }
        
        
        if(a.equals("") || a.equals(null))
        {
            MaxDesigns.getInstance().writeCon();
            JOptionPane.showMessageDialog(this,"The Data has been Updated Successfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now(); 
            data += "Date/Time : "+dtf.format(now)+"\n";
            data += "                                     MAX DESIGNS\n";
            data += "_______________________________________________________________________________________\n\n";
            MaxDesigns.getInstance().SeperateCon(n,data);
        }
    }//GEN-LAST:event_upBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JTextField cnicTxt;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel invalidAmount;
    private javax.swing.JLabel invalidCnic;
    private javax.swing.JLabel invalidContact;
    private javax.swing.JLabel invalidName;
    private javax.swing.JLabel invalidOwner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField ownerTxt;
    private javax.swing.JButton srchBtn;
    private javax.swing.JButton upBtn;
    // End of variables declaration//GEN-END:variables
}
