/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author DEll
 */
public class VendorDetails extends javax.swing.JInternalFrame {

    public int index = -1;
    
    public String data = "";
    
    /**
     * Creates new form VendorDetails
     */
    public VendorDetails() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        saleTxt.setEnabled(false);
        projectTxt.setEnabled(false);
        detailTxt.setEnabled(false);
        submitBtn.setEnabled(false);
    }
    
    public boolean isValidName(String name)
    {
        int size = name.length();
        boolean flag=false;
        
        for(int i =0;i<size;i++)
        {
            if((name.charAt(i)>='A' && name.charAt(i)<='Z')||(name.charAt(i)>='a' && name.charAt(i)<='z')||(name.charAt(i)==' ') || (name.charAt(i)>='0' && name.charAt(i)<='9') || (name.charAt(i)=='-'))
            {
                flag = true;
            }
            else
                return false;
        }
        return flag;
        
    }
    
    public String fileData(String company)
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               Vending Details\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Umair Umar | Administrator\n\n";
               s += "Vendor's Company : "+company+"\n";
               return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vendorTxt = new javax.swing.JTextField();
        srchBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        saleTxt = new javax.swing.JTextField();
        invalidSale = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        projectTxt = new javax.swing.JTextField();
        proTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTxt = new javax.swing.JTextArea();
        submitBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(920, 787));

        kGradientPanel1.setkEndColor(new java.awt.Color(24, 24, 24));
        kGradientPanel1.setkStartColor(new java.awt.Color(186, 139, 2));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 169, 91));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Vendor Details");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, -1, 80));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-contact-details-80.png"))); // NOI18N
        jLabel3.setText("Detail Portal");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Vendor Name :");

        vendorTxt.setBackground(new java.awt.Color(212, 209, 209));
        vendorTxt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        vendorTxt.setForeground(new java.awt.Color(51, 0, 51));
        vendorTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        vendorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorTxtActionPerformed(evt);
            }
        });

        srchBtn.setBackground(new java.awt.Color(255, 153, 0));
        srchBtn.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        srchBtn.setForeground(new java.awt.Color(255, 255, 255));
        srchBtn.setText("Search");
        srchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 3));
        srchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBtnActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(153, 0, 0));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Sale :");

        saleTxt.setBackground(new java.awt.Color(212, 209, 209));
        saleTxt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        saleTxt.setForeground(new java.awt.Color(51, 0, 51));
        saleTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        saleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleTxtActionPerformed(evt);
            }
        });

        invalidSale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invalidSale.setForeground(new java.awt.Color(153, 0, 0));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Project Name:");

        projectTxt.setBackground(new java.awt.Color(212, 209, 209));
        projectTxt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        projectTxt.setForeground(new java.awt.Color(51, 0, 51));
        projectTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        projectTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectTxtActionPerformed(evt);
            }
        });

        proTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        proTxt.setForeground(new java.awt.Color(153, 0, 0));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("<html>\nSale\n<br>\nDetials :");

        detailTxt.setBackground(new java.awt.Color(212, 209, 209));
        detailTxt.setColumns(20);
        detailTxt.setFont(new java.awt.Font("Ebrima", 0, 17)); // NOI18N
        detailTxt.setForeground(new java.awt.Color(51, 0, 51));
        detailTxt.setRows(5);
        detailTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));
        jScrollPane1.setViewportView(detailTxt);

        submitBtn.setBackground(new java.awt.Color(255, 153, 0));
        submitBtn.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 3));
        submitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(srchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vendorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invalidSale, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(46, 46, 46)
                                .addComponent(saleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(projectTxt))))
                        .addGap(65, 65, 65))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vendorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(srchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidSale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 630, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vendorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorTxtActionPerformed

    private void saleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleTxtActionPerformed

    private void projectTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectTxtActionPerformed

    private void srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBtnActionPerformed
        // TODO add your handling code here:
        String name = vendorTxt.getText();
        
        if(name.equals("") || name.equals(null))
        {
            JOptionPane.showMessageDialog(this,"You first need to search the Vendor for which\nthe data is to be added","Empty Input",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            for(int i = 0;i<MaxDesigns.getInstance().getVen().size();i++)
            {
                if(MaxDesigns.getInstance().getVen().get(i).getCompany().equals(name))
                {
                    this.data = fileData(name);
                    index = i;
                    saleTxt.setEnabled(true);
                    projectTxt.setEnabled(true);
                    detailTxt.setEnabled(true);
                    submitBtn.setEnabled(true);
                    vendorTxt.setEnabled(false);
                    srchBtn.setEnabled(false);
                    break;
                }
                else
                    index=-1;
            }
            if(index == -1)
                JOptionPane.showMessageDialog(this,"The following Vendor Does not seem to present in our data\nTry again with something else","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_srchBtnActionPerformed

    public void addData(String project)
    {
        
        int Oindex = -1;
        for(int i = 0; i<MaxDesigns.getInstance().getDes().size();i++)
        {
            if(MaxDesigns.getInstance().getDes().get(i).getName().equals(project))
            {
                Oindex = i;
                data += "Project Name : " + project+" ( "+MaxDesigns.getInstance().getDes().get(i).getId()+" )\n";
                data += "Owner : "+MaxDesigns.getInstance().getDes().get(i).getOwner()+"\n";
                data += "Vendor : "+MaxDesigns.getInstance().getVen().get(index).getCompany()+"( "+MaxDesigns.getInstance().getVen().get(index).getId()+" )\n";
                data += "Vendor Type :"+MaxDesigns.getInstance().getVen().get(index).getType()+"\n";
                data += "Vendor Owner :"+MaxDesigns.getInstance().getVen().get(index).getOwner()+"\n";
                break;
            }
            else
                Oindex = -1;
        }
        if(Oindex == -1)
        {
            for(int i = 0; i<MaxDesigns.getInstance().getCon().size();i++)
            {
                if(MaxDesigns.getInstance().getCon().get(i).getName().equals(project))
                {
                    Oindex = i;
                    data += "Project Name : " + project+" ( "+MaxDesigns.getInstance().getCon().get(i).getId()+" )\n";
                    data += "Owner : "+MaxDesigns.getInstance().getCon().get(i).getOwner()+"\n";
                    data += "Vendor : "+MaxDesigns.getInstance().getVen().get(index).getCompany()+"( "+MaxDesigns.getInstance().getVen().get(index).getId()+" )\n";
                    data += "Vendor Type :"+MaxDesigns.getInstance().getVen().get(index).getType()+"\n";
                    data += "Vendor Owner :"+MaxDesigns.getInstance().getVen().get(index).getOwner()+"\n";
                    break;
                }
                else
                    Oindex = -1;
            }
            if(Oindex == -1)
            {
                data += "Project Name : " + project+" ( Not Present in Data )\n";
                data += "Owner : No Details Avaialable Yet\n";
                data += "Vendor : "+MaxDesigns.getInstance().getVen().get(index).getCompany()+"( "+MaxDesigns.getInstance().getVen().get(index).getId()+" )\n";
                data += "Vendor Type :"+MaxDesigns.getInstance().getVen().get(index).getType()+"\n";
                data += "Vendor Owner :"+MaxDesigns.getInstance().getVen().get(index).getOwner()+"\n";
            }
        }
    }
    
    
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String sale = saleTxt.getText();
        String project = projectTxt.getText();
        String details = detailTxt.getText();
        
        if(sale.equals("") || sale.equals(null) || project.equals("") || project.equals(null) || details.equals("") || details.equals(null))
        {
            if(sale.equals("") || sale.equals(null))
            {
                invalidSale.setText("This field is Empty");
            }
            else
                invalidSale.setText("");
            
            if(project.equals("") || project.equals(null))
            {
                proTxt.setText("This field is Empty");
            }
            else
                proTxt.setText("");
            
            if(details.equals("") || details.equals(null))
            {
              JOptionPane.showMessageDialog(this,"You need to enter Some details First","Empty Area",JOptionPane.ERROR_MESSAGE);  
            }
        }
        else
        {
            int Oindex = -1;
            
            if(isValidName(project))
            {
                proTxt.setText("");
                addData(project);
                //System.out.print("The data is "+data);
                if(MaxDesigns.getInstance().getVen().get(index).isDigits(sale))
                {
                    
                    invalidSale.setText("");
                    int am = Integer.parseInt(sale);
                    if(am > 0)
                    {
                        invalidSale.setText("");
                        double send = am * (MaxDesigns.getInstance().getVen().get(index).getSharePer()/100);
                        int s = (int)send;
                        if(MaxDesigns.getInstance().getVen().get(index).addMoney(s))
                        {
                            data += "The Amount of which the profit has been granted is Rs : "+sale+"\n";
                            invalidSale.setText("");
                            data += "The Details are as follows :\n\n";
                            data += details;
                            data += "\n\n                                               MAX DESIGNS\n";
                            data += "_________________________________________________________________________________\n\n";
                            MaxDesigns.getInstance().VenWrite(data);
                            MaxDesigns.getInstance().writeVen();
                            JOptionPane.showMessageDialog(this,"Data has been Added Successfully","Congratulations :)",JOptionPane.INFORMATION_MESSAGE);
                            saleTxt.setText("");
                            projectTxt.setText("");
                            detailTxt.setText("");
                            vendorTxt.setText("");
                            saleTxt.setEnabled(false);
                            projectTxt.setEnabled(false);
                            detailTxt.setEnabled(false);
                            submitBtn.setEnabled(false);
                            vendorTxt.setEnabled(true);
                            srchBtn.setEnabled(true);
                        }
                        else
                            invalidSale.setText("The amount should be greater than 0");
                    }
                    else
                    invalidSale.setText("The amount should be greater than 0");
                }
                else
                    invalidSale.setText("The amount should be in digits");
                
            }
            else
                proTxt.setText("Only Alphabets and Spaces are Allowed");
        }
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea detailTxt;
    private javax.swing.JLabel invalidSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel proTxt;
    private javax.swing.JTextField projectTxt;
    private javax.swing.JTextField saleTxt;
    private javax.swing.JButton srchBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField vendorTxt;
    // End of variables declaration//GEN-END:variables
}
