/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maxdesigns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author DEll
 */
public class VendorTransaction extends javax.swing.JInternalFrame {

    int index = -1;
    String text = "";
    
    /**
     * Creates new form VendorTransaction
     */
    public VendorTransaction() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        payText.setEnabled(false);
        subBtn.setEnabled(false);
    }
    
    public String fileData(int index)
    {
        String s = "\n\n*****************************************************************************\n";
               s += "                               UPDATE VENDOR\n";
               s += "____________________________________________________________________________\n";
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
                LocalDateTime now = LocalDateTime.now(); 
               s += "Date/Time : "+dtf.format(now)+"                        Umair Umar | Administrator\n\n";
               s += "Account Details to be Updated. .................................. \n\n";
               s += "Vendor Name : "+MaxDesigns.getInstance().getVen().get(index).getCompany()+" ( "+MaxDesigns.getInstance().getVen().get(index).getId()+" )\n";
               s += "Owner Name : "+MaxDesigns.getInstance().getVen().get(index).getOwner()+"\n";
               s += "Before Balance : "+MaxDesigns.getInstance().getVen().get(index).getBalance()+"\n";
               
               return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vendorTxt = new javax.swing.JTextField();
        srchBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ownLabel = new javax.swing.JLabel();
        balLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        payText = new javax.swing.JTextField();
        invalidPayment = new javax.swing.JLabel();
        subBtn = new com.k33ptoo.components.KButton();

        setPreferredSize(new java.awt.Dimension(920, 787));

        kGradientPanel1.setkEndColor(new java.awt.Color(24, 24, 24));
        kGradientPanel1.setkStartColor(new java.awt.Color(186, 139, 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/watermark.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxdesigns/icons8-transaction-24.png"))); // NOI18N
        jLabel1.setText("Transaction");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Vendor Name :");

        vendorTxt.setBackground(new java.awt.Color(212, 209, 209));
        vendorTxt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        vendorTxt.setForeground(new java.awt.Color(51, 0, 51));
        vendorTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        vendorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorTxtActionPerformed(evt);
            }
        });

        srchBtn.setBackground(new java.awt.Color(255, 153, 0));
        srchBtn.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        srchBtn.setForeground(new java.awt.Color(255, 255, 255));
        srchBtn.setText("Search");
        srchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 3));
        srchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBtnActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        ownLabel.setFont(new java.awt.Font("Calibri", 1, 34)); // NOI18N
        ownLabel.setForeground(new java.awt.Color(255, 255, 255));
        ownLabel.setText("Owner Name");

        balLabel.setFont(new java.awt.Font("Calibri", 1, 34)); // NOI18N
        balLabel.setForeground(new java.awt.Color(255, 255, 255));
        balLabel.setText("Your Balance");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Payment :");

        payText.setBackground(new java.awt.Color(240, 240, 240));
        payText.setFont(new java.awt.Font("Charlemagne Std", 1, 18)); // NOI18N
        payText.setForeground(new java.awt.Color(51, 0, 51));
        payText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 0, 51)));

        invalidPayment.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        invalidPayment.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(payText)
                    .addComponent(invalidPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(payText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(invalidPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        subBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        subBtn.setText("SUBMIT");
        subBtn.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        subBtn.setkEndColor(new java.awt.Color(24, 24, 24));
        subBtn.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        subBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        subBtn.setkHoverStartColor(new java.awt.Color(0, 0, 153));
        subBtn.setkStartColor(new java.awt.Color(186, 139, 2));
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ownLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(balLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(srchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(vendorTxt)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(vendorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(srchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownLabel)
                    .addComponent(balLabel))
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vendorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorTxtActionPerformed

    private void srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBtnActionPerformed
        // TODO add your handling code here:
        String name = vendorTxt.getText();
        
        if(name.equals("") || name.equals(null))
        {
            JOptionPane.showMessageDialog(this,"You first need to search the Name of the vendor","Empty Field",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            for(int i = 0;i<MaxDesigns.getInstance().getVen().size();i++)
            {
                if(MaxDesigns.getInstance().getVen().get(i).getCompany().equals(name))
                {
                    index = i;
                    this.text = fileData(index);
                    break;
                }
            }
            if(index == -1 )
            {
                JOptionPane.showMessageDialog(this,"Vendor Not Found","Error",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                vendorTxt.setEnabled(false);
                srchBtn.setEnabled(false);
                payText.setEnabled(true);
                subBtn.setEnabled(true);
                ownLabel.setText(MaxDesigns.getInstance().getVen().get(index).getOwner());
                balLabel.setText("Rs : "+MaxDesigns.getInstance().getVen().get(index).getBalance()+" /-");
                
            }
        }
    }//GEN-LAST:event_srchBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        String amount = payText.getText();
        
        if(amount.equals("") || amount.equals(null))
        {
            JOptionPane.showMessageDialog(this,"You first need to Enter the Amount for transaction","Empty Field",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(MaxDesigns.getInstance().getVen().get(index).isDigits(amount))
            {
                int am = Integer.parseInt(amount);
                if(am>0)
                {
                    if(MaxDesigns.getInstance().getVen().get(index).isAvailable(am))
                    {
                        MaxDesigns.getInstance().getVen().get(index).withdraw(am);
                        text += "The amount withdrawn is Rs : "+am+"\n";
                        text += "After Balance : "+MaxDesigns.getInstance().getVen().get(index).getBalance()+"\n\n\n";
                        text += "                                                 MAX DESIGNS\n";
                        text += "__________________________________________________________________________________________\n";
                        MaxDesigns.getInstance().VenWrite(text);
                        balLabel.setText("Rs : "+MaxDesigns.getInstance().getVen().get(index).getBalance()+" /-");
                        MaxDesigns.getInstance().writeVen();
                        JOptionPane.showMessageDialog(this,"Transaction Completed...","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                        
                        
                    }
                    else
                        invalidPayment.setText("The Balance is less than the given amount");
                }
                else
                    invalidPayment.setText("Amount should be greater than 0");
            }
            else
                invalidPayment.setText("Amount should be in digits");
        }
    }//GEN-LAST:event_subBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balLabel;
    private javax.swing.JLabel invalidPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel ownLabel;
    private javax.swing.JTextField payText;
    private javax.swing.JButton srchBtn;
    private com.k33ptoo.components.KButton subBtn;
    private javax.swing.JTextField vendorTxt;
    // End of variables declaration//GEN-END:variables
}
